import type { FreshProduct } from './freshProductImport';

export const catalogExpansionProducts: FreshProduct[] = [
  {
    title: 'Waterproof Golf Valuables Pouch',
    handle: 'waterproof-golf-valuables-pouch-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Accessories',
    price: '39.99',
    compareAtPrice: '49.99',
    description: 'A waterproof valuables pouch candidate for phones, keys, wallets, tees, and markers on golf trips and wet-weather rounds.',
    details: ['Trip and cart utility without sizing risk', 'Good add-on for bag organization and golf travel pages', 'Must confirm waterproof claims, supplier photos, and return terms before activation'],
    sku: 'WYX-SR-WATERPROOF-POUCH',
    quantity: 0,
    sourceUrl: 'supplier-review:Spocket, Doba, CJ, or approved golf pouch supplier',
    tags: ['supplier-review', 'bag-organization', 'trip-gear', 'golf gifts', 'under-50'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Cart Cooler Sleeve',
    handle: 'golf-cart-cooler-sleeve-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Trip Gear',
    price: '44.99',
    compareAtPrice: '54.99',
    description: 'A discreet golf cart cooler sleeve candidate for road trips, buddy weekends, and long summer rounds.',
    details: ['Strong bachelor-party and trip-kit fit', 'Lightweight product with clear lifestyle use case', 'Supplier must confirm insulation quality, dimensions, and shipping speed before activation'],
    sku: 'WYX-SR-CART-COOLER',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Zendrop, CJ, or approved golf cooler supplier',
    tags: ['supplier-review', 'trip-gear', 'golf gifts', 'cart-gear', 'under-60'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Shoe Travel Bag',
    handle: 'golf-shoe-travel-bag-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Trip Gear',
    price: '34.99',
    compareAtPrice: '44.99',
    description: 'A golf shoe travel bag candidate for trunk organization, weekend trips, and keeping spikes away from clean gear.',
    details: ['Practical travel product golfers understand immediately', 'Pairs well with trip kits and apparel', 'Needs real product photos showing size, ventilation, and storage pockets'],
    sku: 'WYX-SR-SHOE-BAG',
    quantity: 0,
    sourceUrl: 'supplier-review:Spocket, Doba, CJ, or golf travel accessory supplier',
    tags: ['supplier-review', 'trip-gear', 'bag-organization', 'golf gifts', 'under-50'],
    status: 'DRAFT'
  },
  {
    title: 'Ball Line Marker Stencil Kit',
    handle: 'ball-line-marker-stencil-kit-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Accessories',
    price: '12.99',
    compareAtPrice: '16.99',
    description: 'A ball line marker stencil kit candidate for golfers who want a simple putting alignment add-on in the cart.',
    details: ['Low-cost checkout add-on with strong attach potential', 'Easy bundle companion for balls, markers, and putting aids', 'Must confirm marker quality and packaging before activation'],
    sku: 'WYX-SR-BALL-LINE-KIT',
    quantity: 0,
    sourceUrl: 'supplier-review:JP Lann, GT Golf Supply, Doba, or approved golf accessory supplier',
    tags: ['supplier-review', 'putting', 'golf gifts', 'cart-add-on', 'under-15'],
    status: 'DRAFT'
  },
  {
    title: 'Retractable Club Brush',
    handle: 'retractable-club-brush-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Club Care',
    price: '16.99',
    compareAtPrice: '21.99',
    description: 'A retractable club brush candidate for quick groove cleaning between shots and better contact during real rounds.',
    details: ['Clear utility and easy under-$20 gift', 'Pairs naturally with towels and clean-contact kits', 'Needs real supplier image and bristle/material details before activation'],
    sku: 'WYX-SR-RETRACTABLE-BRUSH',
    quantity: 0,
    sourceUrl: 'supplier-review:JP Lann, GT Golf Supply, CJ, or approved club-care supplier',
    tags: ['supplier-review', 'club-care', 'bag-upgrade', 'clean-contact', 'under-20'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Alignment Sticks - 2 Pack',
    handle: 'golf-alignment-sticks-2-pack-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '24.99',
    compareAtPrice: '34.99',
    description: 'A two-pack alignment stick candidate for range sessions, setup checks, and simple practice routines.',
    details: ['Training product with low complexity and broad golfer use', 'Good range-gear collection anchor', 'Supplier must provide durable tube/packaging and color-specific images'],
    sku: 'WYX-SR-ALIGNMENT-STICKS',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, CJ, GT Golf Supply, or approved training-aid supplier',
    tags: ['supplier-review', 'training-aid', 'range-gear', 'golf gifts', 'under-35'],
    status: 'DRAFT'
  },
  {
    title: 'Putting Gate Trainer Set',
    handle: 'putting-gate-trainer-set-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '22.99',
    compareAtPrice: '29.99',
    description: 'A compact putting gate trainer candidate for grooving start line and face control at home or on the practice green.',
    details: ['Small, giftable training aid with obvious use case', 'Pairs with the putting mirror for an improvement bundle', 'Needs demo images or video before activation'],
    sku: 'WYX-SR-PUTTING-GATE',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, CJ, or approved putting training supplier',
    tags: ['supplier-review', 'training-aid', 'putting', 'golf gifts', 'under-30'],
    status: 'DRAFT'
  },
  {
    title: 'Indoor Putting Mat',
    handle: 'indoor-putting-mat-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '69.99',
    compareAtPrice: '89.99',
    description: 'An indoor putting mat candidate for golfers who want useful practice at home without buying a bulky simulator setup.',
    details: ['Good higher-AOV training product under $100', 'Must be compact enough to ship profitably', 'Only activate with supplier dimensions, return terms, and real lifestyle media'],
    sku: 'WYX-SR-PUTTING-MAT',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Zendrop, CJ, or approved putting mat supplier',
    tags: ['supplier-review', 'training-aid', 'putting', 'golf gifts', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Portable Chipping Net',
    handle: 'portable-chipping-net-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '39.99',
    compareAtPrice: '49.99',
    description: 'A portable chipping net candidate for backyard wedge practice and golfers who want a simple way to sharpen short game.',
    details: ['Training aid with strong home-practice appeal', 'Giftable under-$50 price point', 'Check fold quality, shipping dimensions, and return rate before activation'],
    sku: 'WYX-SR-CHIPPING-NET',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, CJ, Zendrop, or approved short-game training supplier',
    tags: ['supplier-review', 'training-aid', 'short-game', 'golf gifts', 'under-50'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Bag Organizer Insert',
    handle: 'golf-bag-organizer-insert-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Bag Organization',
    price: '29.99',
    compareAtPrice: '39.99',
    description: 'A bag organizer insert candidate for tees, gloves, markers, valuables, and the small accessories that disappear mid-round.',
    details: ['Strong bag-upgrade fit and low sizing risk', 'Supports kit building and upsells', 'Needs photos showing pockets, scale, and bag compatibility'],
    sku: 'WYX-SR-BAG-ORGANIZER',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Spocket, CJ, or golf accessory supplier',
    tags: ['supplier-review', 'bag-organization', 'bag-upgrade', 'golf gifts', 'under-40'],
    status: 'DRAFT'
  },
  {
    title: 'Premium Golf Socks - 3 Pack',
    handle: 'premium-golf-socks-3-pack-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Apparel',
    price: '24.99',
    compareAtPrice: '34.99',
    description: 'A premium golf sock three-pack candidate for apparel expansion without the fit risk of shirts and pants.',
    details: ['Low-risk apparel add-on with repeat-purchase potential', 'Good gift and trip packing product', 'Activate only with accurate sizing, fabric content, and color images'],
    sku: 'WYX-SR-SOCKS-3PK',
    quantity: 0,
    sourceUrl: 'supplier-review:Printful, Printify, Bear Grips, or apparel dropship supplier',
    tags: ['supplier-review', 'apparel', 'golf gifts', 'trip-gear', 'under-35'],
    status: 'DRAFT'
  },
  {
    title: 'Performance Golf Hoodie',
    handle: 'performance-golf-hoodie-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Apparel',
    price: '64.99',
    compareAtPrice: '79.99',
    description: 'A performance golf hoodie candidate for early tee times, travel days, and the course-to-bar weekend golfer look.',
    details: ['Higher-AOV apparel product with lifestyle appeal', 'Start with two neutral colors and a clear size chart', 'Do not activate until blank quality, returns, and fit photos are verified'],
    sku: 'WYX-SR-PERFORMANCE-HOODIE',
    quantity: 0,
    sourceUrl: 'supplier-review:Bear Grips, Printful, Printify, or approved apparel supplier',
    tags: ['supplier-review', 'apparel', 'golf hoodie', 'trip-gear', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Budget Golf GPS Speaker',
    handle: 'budget-golf-gps-speaker-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Tech',
    price: '89.99',
    compareAtPrice: '119.99',
    description: 'A budget GPS speaker candidate for golfers who want cart audio and distance help without premium tech pricing.',
    details: ['Potential high-AOV tech product for cart golfers', 'Only activate with warranty, app/support clarity, and real product reviews', 'Good fit for trip gear if quality is proven'],
    sku: 'WYX-SR-GPS-SPEAKER',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Zendrop, or approved golf tech supplier with warranty',
    tags: ['supplier-review', 'golf tech', 'trip-gear', 'premium', 'cart-gear'],
    status: 'DRAFT'
  },
  {
    title: 'Rangefinder Hard Case',
    handle: 'rangefinder-hard-case-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Tech',
    price: '19.99',
    compareAtPrice: '24.99',
    description: 'A rangefinder hard case candidate for protecting golf tech in the cart, trunk, and travel bag.',
    details: ['Useful add-on if WYX carries rangefinders', 'Easy under-$25 accessory with low return risk', 'Must verify dimensions and compatibility claims'],
    sku: 'WYX-SR-RANGEFINDER-CASE',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, CJ, or rangefinder accessory supplier',
    tags: ['supplier-review', 'golf tech', 'bag-upgrade', 'cart-add-on', 'under-25'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Travel Essentials Bundle',
    handle: 'golf-travel-essentials-bundle',
    vendor: 'WYX Golf Supply Co.',
    productType: 'Golf Gift Bundle',
    price: '79.99',
    compareAtPrice: '99.99',
    description: 'A golf travel bundle candidate built around a shoe bag, valuables pouch, towel, tees, and markers for the next weekend trip.',
    details: ['Raises AOV while keeping the catalog curated', 'Only bundle confirmed supplier products with matching real images', 'Strong landing-page and email campaign product'],
    sku: 'WYX-BUNDLE-TRAVEL-ESSENTIALS',
    quantity: 0,
    sourceUrl: 'bundle-review:assemble from approved Shopify products',
    tags: ['supplier-review', 'bundle', 'trip-gear', 'golf gifts', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Short Game Practice Bundle',
    handle: 'short-game-practice-bundle',
    vendor: 'WYX Golf Supply Co.',
    productType: 'Golf Gift Bundle',
    price: '89.99',
    compareAtPrice: '109.99',
    description: 'A short game practice bundle candidate combining a putting mirror, putting gate, and chipping net for golfers trying to score better.',
    details: ['Creates a focused improvement kit instead of random training SKUs', 'Good gift and SEO landing-page target', 'Only activate after every component has confirmed fulfillment and real media'],
    sku: 'WYX-BUNDLE-SHORT-GAME',
    quantity: 0,
    sourceUrl: 'bundle-review:assemble from approved training products',
    tags: ['supplier-review', 'bundle', 'training-aid', 'putting', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Clean Contact Bundle',
    handle: 'clean-contact-bundle-supplier-review',
    vendor: 'WYX Golf Supply Co.',
    productType: 'Golf Gift Bundle',
    price: '49.99',
    compareAtPrice: '64.99',
    description: 'A clean-contact bundle candidate with a towel, retractable brush, and groove cleaner for golfers who care about better strikes.',
    details: ['Clear benefit and strong checkout/cart upsell fit', 'Works for dads, scrambles, and first-time buyers', 'Use only real supplier images for each component before activation'],
    sku: 'WYX-BUNDLE-CLEAN-CONTACT',
    quantity: 0,
    sourceUrl: 'bundle-review:assemble from approved club-care products',
    tags: ['supplier-review', 'bundle', 'club-care', 'bag-upgrade', 'golf gifts'],
    status: 'DRAFT'
  }
];
