import type { FreshProduct } from './freshProductImport';

export const nextProductExpansionProducts: FreshProduct[] = [
  {
    title: 'Performance Rope Golf Hat',
    handle: 'performance-rope-golf-hat-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Headwear',
    price: '34.99',
    compareAtPrice: '44.99',
    description: 'A performance rope hat candidate for clean course style, low sizing risk, and strong gift appeal.',
    details: ['Best apparel expansion because sizing risk is low', 'Use only real blank or embroidered product photos', 'Prioritize forest, navy, cream, and black colorways'],
    sku: 'WYX-SR-PERFORMANCE-ROPE-HAT',
    quantity: 0,
    sourceUrl: 'supplier-review:Bear Grips, Printful, Printify, or approved embroidery supplier',
    tags: ['supplier-review', 'headwear', 'golf hats', 'apparel', 'under-40'],
    status: 'DRAFT'
  },
  {
    title: 'Lightweight Golf Quarter Zip',
    handle: 'lightweight-golf-quarter-zip-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Apparel',
    price: '64.99',
    compareAtPrice: '79.99',
    description: 'A lightweight quarter zip candidate for early tee times, travel days, and premium weekend golf layering.',
    details: ['Higher AOV apparel item with clear golf lifestyle fit', 'Requires size chart, fabric details, and real fit photos', 'Start with two neutral colors only'],
    sku: 'WYX-SR-LIGHTWEIGHT-QZ',
    quantity: 0,
    sourceUrl: 'supplier-review:Bear Grips, Printful, Printify, or approved golf apparel supplier',
    tags: ['supplier-review', 'apparel', 'quarter zip', 'trip-gear', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Stretch Golf Belt',
    handle: 'stretch-golf-belt-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Apparel',
    price: '39.99',
    compareAtPrice: '49.99',
    description: 'A stretch golf belt candidate for a cleaner apparel cart without the high return risk of sized tops.',
    details: ['Low sizing risk compared with shirts and pants', 'Pairs well with hats and gloves', 'Must confirm fit range, buckle quality, and color-specific photos'],
    sku: 'WYX-SR-STRETCH-BELT',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Spocket, Bear Grips, or approved apparel accessory supplier',
    tags: ['supplier-review', 'apparel', 'golf belt', 'golf gifts', 'under-50'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Swing Speed Trainer',
    handle: 'golf-swing-speed-trainer-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '59.99',
    compareAtPrice: '79.99',
    description: 'A swing speed trainer candidate for golfers who want a simple warmup and speed-building tool without a bulky training setup.',
    details: ['Strong improvement-product fit with clear before-round use', 'Needs instructions, safety notes, and demo media', 'Only activate if shipping dimensions and return rates are reasonable'],
    sku: 'WYX-SR-SWING-SPEED',
    quantity: 0,
    sourceUrl: 'supplier-review:CJ, Doba, Zendrop, or approved golf training supplier',
    tags: ['supplier-review', 'training-aid', 'swing trainer', 'range-gear', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Grip Trainer',
    handle: 'golf-grip-trainer-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Training Aids',
    price: '19.99',
    compareAtPrice: '29.99',
    description: 'A grip trainer candidate for new golfers, range sessions, and simple swing fundamentals.',
    details: ['Small, lightweight, and easy to gift', 'Pairs with gloves, grip tape, and range-session content', 'Needs clear hand-orientation and compatibility notes'],
    sku: 'WYX-SR-GRIP-TRAINER',
    quantity: 0,
    sourceUrl: 'supplier-review:CJ, Doba, or approved training aid supplier',
    tags: ['supplier-review', 'training-aid', 'grip trainer', 'range-gear', 'under-25'],
    status: 'DRAFT'
  },
  {
    title: 'Compact Slope Golf Rangefinder',
    handle: 'compact-slope-golf-rangefinder-supplier-review',
    vendor: 'Supplier Review',
    productType: 'Golf Tech',
    price: '119.99',
    compareAtPrice: '149.99',
    description: 'A compact slope rangefinder candidate for weekend golfers who want accurate yardages without premium tech pricing.',
    details: ['High AOV tech candidate with clear utility', 'Requires warranty, returns, battery details, and real reviews', 'Only activate if fulfillment and support are reliable'],
    sku: 'WYX-SR-SLOPE-RANGEFINDER',
    quantity: 0,
    sourceUrl: 'supplier-review:Doba, Zendrop, or approved rangefinder supplier with warranty',
    tags: ['supplier-review', 'golf tech', 'rangefinder', 'training-aid', 'premium'],
    status: 'DRAFT'
  },
  {
    title: 'Golf Towel + Brush Cart Kit',
    handle: 'golf-towel-brush-cart-kit',
    vendor: 'WYX Golf Supply Co.',
    productType: 'Golf Gift Bundle',
    price: '39.99',
    compareAtPrice: '54.99',
    description: 'A towel and brush bundle candidate for golfers who want cleaner clubs, cleaner hands, and one useful cart add-on.',
    details: ['Simple first-purchase bundle with obvious utility', 'Use only verified towel and brush products with real media', 'Good upsell from towel, brush, and club-care pages'],
    sku: 'WYX-BUNDLE-TOWEL-BRUSH',
    quantity: 0,
    sourceUrl: 'bundle-review:assemble from approved towel and club-care products',
    tags: ['supplier-review', 'bundle', 'club-care', 'bag-upgrade', 'golf gifts'],
    status: 'DRAFT'
  }
];
