export type Money = { amount: string; currencyCode: string };
export type ShopifyImage = { url: string; altText?: string | null; width?: number; height?: number };
export type ProductVariant = { id: string; title: string; availableForSale: boolean; price: Money; sku?: string | null; barcode?: string | null; selectedOptions?: Array<{ name: string; value: string }>; image?: ShopifyImage | null };
export type Product = {
  id: string;
  handle: string;
  title: string;
  description: string;
  descriptionHtml?: string;
  vendor?: string;
  availableForSale: boolean;
  featuredImage?: ShopifyImage | null;
  images: ShopifyImage[];
  variants: ProductVariant[];
  priceRange: { minVariantPrice: Money };
  tags?: string[];
  productType?: string;
};
export type CartLine = { id: string; quantity: number; merchandise: { id: string; title: string; product: { title: string; handle: string; featuredImage?: ShopifyImage | null }; price: Money }; cost: { totalAmount: Money } };
export type Cart = { id: string; checkoutUrl: string; totalQuantity: number; discountCodes?: Array<{ code: string; applicable: boolean }>; cost: { subtotalAmount: Money; totalAmount: Money }; lines: CartLine[] };
