export type StarterProduct = {
  title: string;
  handle: string;
  price: string;
  badge: string;
  image: string;
  productType: string;
  collectionHandle: string;
  description: string;
  details: string[];
  materials: string;
  care: string;
  seoTitle: string;
  metaDescription: string;
  tags: string[];
};

export const imageMap = {
  hero: '/images/hero-coastal-fairway.png',
  ropeHat: '/images/rope-hat-product.png',
  polo: '/images/forest-polo-product.png',
  towel: '/images/golf-towel-product.png',
  walk: '/images/walking-golfer-lifestyle..png',
  leather: '/images/leather-bag-detail.png',
  iron: '/images/journal-iron-practice.png',
  care: '/images/journal-club-care.png',
  strategy: '/images/journal-course-strategy.png'
};

export const starterProducts: StarterProduct[] = [
  {
    title: 'The Long Game Rope Hat',
    handle: 'long-game-rope-hat',
    price: '68.00',
    badge: 'Core Collection',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A cream rope hat with restrained WYX embroidery, made for course mornings, travel days, and everything after the round.',
    details: ['Structured five-panel profile', 'Rope detail across the brim', 'Adjustable back closure', 'Designed for course, coast, and travel'],
    materials: 'Cotton canvas crown with woven rope detail and embroidered WYX mark.',
    care: 'Spot clean with cold water. Air dry away from direct heat.',
    seoTitle: 'Golf Rope Hat | WYX Golf Supply Co.',
    metaDescription: 'A premium golf rope hat with restrained WYX embroidery for early tee times, travel days, and life after the round.',
    tags: ['core collection', 'golf rope hat', 'premium golf apparel', 'headwear', 'best seller']
  },
  {
    title: 'The Fairway Polo',
    handle: 'fairway-polo',
    price: '128.00',
    badge: 'Core Collection',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A forest green polo with clean structure, quiet detail, and the kind of everyday polish that works far beyond the first tee.',
    details: ['Tailored athletic fit', 'Clean collar structure', 'Subtle WYX detail', 'Built for rounds, travel, and clubhouse evenings'],
    materials: 'Performance knit with soft hand feel and enough structure to hold its shape.',
    care: 'Machine wash cold with like colors. Hang dry or tumble low.',
    seoTitle: 'Premium Golf Polo | WYX Golf Supply Co.',
    metaDescription: 'A forest green premium golf polo with clean structure and quiet WYX detail for course and everyday wear.',
    tags: ['core collection', 'golf polo', 'premium golf apparel', 'apparel']
  },
  {
    title: 'The Waffle Golf Towel',
    handle: 'waffle-golf-towel',
    price: '42.00',
    badge: 'New',
    image: imageMap.towel,
    productType: 'Gear',
    collectionHandle: 'golf-gear',
    description: 'A premium waffle towel with forest trim, built for the bag and styled for the long game.',
    details: ['Waffle texture for club and ball cleaning', 'Bag-ready attachment loop', 'Forest trim detail', 'Sized for walking rounds and travel bags'],
    materials: 'Absorbent waffle microfiber with reinforced trim.',
    care: 'Machine wash cold. Do not use fabric softener. Air dry for best texture.',
    seoTitle: 'Premium Golf Towel | WYX Golf Supply Co.',
    metaDescription: 'A premium waffle golf towel with forest trim for clean clubs, ready gear, and quiet-luxury golf style.',
    tags: ['new arrivals', 'golf towel', 'golf accessories', 'walking golf', 'best seller']
  },
  {
    title: 'Leather Bag Tag',
    handle: 'leather-bag-tag',
    price: '54.00',
    badge: 'Limited',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A small detail with lasting presence. Built to bring a quiet mark of identity to your golf bag.',
    details: ['Leather-look finish', 'WYX identity mark', 'Bag strap included', 'Gift-ready accessory for golfers'],
    materials: 'Premium leather-style material with durable attachment hardware.',
    care: 'Wipe clean with a dry cloth. Keep away from prolonged soaking.',
    seoTitle: 'Leather Golf Bag Tag | WYX Golf Supply Co.',
    metaDescription: 'A premium leather golf bag tag made for players who value quiet detail and timeless golf accessories.',
    tags: ['limited', 'golf accessories', 'golf gifts', 'bag tag']
  },
  {
    title: 'Club Care Kit',
    handle: 'club-care-kit',
    price: '48.00',
    badge: 'Core Collection',
    image: imageMap.care,
    productType: 'Club Care',
    collectionHandle: 'club-care',
    description: 'Everything needed to keep grooves clean, gear ready, and the ritual intact.',
    details: ['Compact brush and groove tool', 'Bag-friendly cleaning cloth', 'Simple weekly reset routine', 'Designed for irons, wedges, and everyday rounds'],
    materials: 'Mixed club-care tools selected for compact carry and weekly use.',
    care: 'Rinse brush after use and dry before returning to the bag.',
    seoTitle: 'Golf Club Care Kit | WYX Golf Supply Co.',
    metaDescription: 'A compact golf club care kit for keeping grooves clean, gear ready, and the weekly golf ritual intact.',
    tags: ['core collection', 'golf club care', 'club cleaning kit', 'golf essentials']
  },
  {
    title: 'WYX Golf Ball Set',
    handle: 'wyx-golf-ball-set',
    price: '36.00',
    badge: 'New',
    image: imageMap.iron,
    productType: 'Gear',
    collectionHandle: 'golf-gear',
    description: 'A clean branded ball set for players who care about every detail, even the small ones.',
    details: ['Clean WYX mark', 'Three-ball set placeholder', 'Made for gifts, travel bags, and early rounds', 'Pairs well with towel and club care kit'],
    materials: 'Performance golf ball placeholder product for Shopify setup.',
    care: 'Keep dry and clean before play. Replace when cover wear affects performance.',
    seoTitle: 'WYX Golf Ball Set | WYX Golf Supply Co.',
    metaDescription: 'A clean WYX golf ball set for players who care about every detail in their modern golf goods.',
    tags: ['new arrivals', 'golf balls', 'golf gifts', 'golf essentials']
  },
  {
    title: 'The Course Pouch',
    handle: 'course-pouch',
    price: '42.00',
    badge: 'New Arrival',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A restrained valuables pouch for tees, markers, gloves, keys, and the small objects that make a round feel organized.',
    details: ['Compact valuables storage', 'Bag and travel friendly', 'Ideal for tees, markers, glove, wallet, and keys', 'Premium gift profile'],
    materials: 'Waxed-canvas style shell with durable zipper and soft internal structure.',
    care: 'Wipe clean. Let air dry fully before storing.',
    seoTitle: 'Golf Valuables Pouch | WYX Golf Supply Co.',
    metaDescription: 'A premium golf valuables pouch for tees, ball markers, gloves, keys, and organized walking rounds.',
    tags: ['new arrivals', 'golf valuables pouch', 'golf accessories', 'golf gifts']
  },
  {
    title: 'Divot Tool + Ball Marker Set',
    handle: 'divot-tool-ball-marker-set',
    price: '34.00',
    badge: 'Golf Gifts',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'golf-gifts',
    description: 'A clean repair tool and marker set with enough weight to feel permanent without drawing attention to itself.',
    details: ['Divot repair tool', 'Matching ball marker', 'Small, giftable, and easy to carry', 'Built around course care and quiet detail'],
    materials: 'Brass-tone metal placeholder product for supplier sampling.',
    care: 'Wipe dry after wet rounds. Store in pouch between rounds.',
    seoTitle: 'Golf Divot Tool and Ball Marker Set | WYX Golf Supply Co.',
    metaDescription: 'A premium golf divot tool and ball marker set for course care, golf gifts, and everyday carry.',
    tags: ['golf gifts', 'divot tool', 'ball marker', 'golf accessories']
  },
  {
    title: 'Golf Travel Organizer',
    handle: 'golf-travel-organizer',
    price: '58.00',
    badge: 'Travel',
    image: imageMap.walk,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A calm way to keep gloves, tees, markers, chargers, and travel-round essentials in one place.',
    details: ['Travel-ready internal organization', 'Works inside a golf bag or weekend bag', 'Built for road trips and away rounds', 'Strong premium gift potential'],
    materials: 'Durable fabric organizer with soft dividers and zipper closure placeholder.',
    care: 'Spot clean and air dry. Empty after wet rounds.',
    seoTitle: 'Golf Travel Organizer | WYX Golf Supply Co.',
    metaDescription: 'A premium golf travel organizer for road trips, away rounds, golf accessories, and course essentials.',
    tags: ['travel', 'golf accessories', 'golf gifts', 'new arrivals']
  },
  {
    title: 'Swing Tempo Trainer',
    handle: 'swing-tempo-trainer',
    price: '44.00',
    badge: 'Training',
    image: imageMap.iron,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'A simple tempo tool that grooves a repeatable swing rhythm. Useful for range sessions, pre-round warmups, and fixing bad habits before they cost strokes.',
    details: ['Weighted tip builds feel for the transition point', 'Works with irons, wedges, and short clubs', 'Compact enough for the bag or travel case', 'Good gift for players serious about improvement'],
    materials: 'Fiberglass shaft with weighted tip and rubber grip.',
    care: 'Wipe clean after use. Store in bag pocket or travel sleeve.',
    seoTitle: 'Golf Swing Tempo Trainer | WYX Golf Supply Co.',
    metaDescription: 'A golf swing tempo trainer for building a repeatable rhythm at the range, pre-round warmup, and home practice.',
    tags: ['training', 'swing trainer', 'training aid', 'golf gifts', 'range gear', 'new arrivals']
  },
  {
    title: 'Laser Rangefinder',
    handle: 'laser-rangefinder',
    price: '129.00',
    badge: 'Golf Tech',
    image: imageMap.strategy,
    productType: 'Golf Tech',
    collectionHandle: 'golf-tech',
    description: 'A clean, pin-seeking laser rangefinder that gives instant yardage to the flag, hazards, and layup targets. The practical upgrade that changes how you think about every approach.',
    details: ['Pin-seeker technology locks to the flag', 'Reads to ±1 yard accuracy', 'Compact and lightweight for bag or pocket carry', 'Strong gift candidate for the serious weekend golfer'],
    materials: 'Durable polymer housing with optical lens and rechargeable or battery power.',
    care: 'Keep dry. Clean lens with soft cloth. Store in included case.',
    seoTitle: 'Golf Laser Rangefinder | WYX Golf Supply Co.',
    metaDescription: 'A compact golf laser rangefinder with pin-seeker technology for accurate yardages on every approach shot.',
    tags: ['golf tech', 'rangefinder', 'laser rangefinder', 'golf gifts', 'dad gifts', 'new arrivals']
  },
  {
    title: 'The Links Snapback',
    handle: 'links-snapback',
    price: '58.00',
    badge: 'Headwear',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A flat-brim snapback with a clean WYX mark. Structured enough for the course, relaxed enough for the rest of the day.',
    details: ['Flat brim with structured crown', 'Snapback closure fits most', 'Embroidered WYX front panel', 'Available in forest and sand colorways'],
    materials: 'Cotton twill crown with embroidered WYX detail and plastic snapback closure.',
    care: 'Spot clean with cold water. Air dry away from direct heat.',
    seoTitle: 'Golf Snapback Hat | WYX Golf Supply Co.',
    metaDescription: 'A flat-brim golf snapback with embroidered WYX detail for course wear, travel days, and everyday carry.',
    tags: ['headwear', 'hat', 'cap', 'golf hat', 'snapback', 'golf gifts', 'new arrivals']
  },
  {
    title: 'The Dad Fit Cap',
    handle: 'dad-fit-cap',
    price: '52.00',
    badge: 'Dad Gifts',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A six-panel unstructured cap with a curved brim. The comfortable, easygoing hat that looks right on the course and off it.',
    details: ['Unstructured six-panel build', 'Pre-curved brim for a broken-in feel', 'Brass buckle back closure', 'Golf dad\'s go-to round hat'],
    materials: 'Garment-washed cotton with tonal embroidery and brass hardware.',
    care: 'Hand wash cold. Air dry. Do not tumble dry.',
    seoTitle: 'Golf Dad Cap | WYX Golf Supply Co.',
    metaDescription: 'A garment-washed unstructured golf dad cap with a curved brim and brass closure — a perfect golf gift for dad.',
    tags: ['headwear', 'hat', 'cap', 'golf hat', 'dad gifts', 'golf gifts for dad', 'new arrivals']
  },
  {
    title: 'The Course Quarter-Zip',
    handle: 'course-quarter-zip',
    price: '148.00',
    badge: 'Apparel',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A course-ready quarter-zip in a midweight performance knit. Clean enough for the clubhouse, warm enough for early tee times and coastal evenings.',
    details: ['Quarter-zip collar with clean pull', 'Midweight warmth for cool rounds', 'Relaxed athletic fit over a polo or base layer', 'WYX tonal detail at chest'],
    materials: 'Midweight performance knit with moisture management and stretch.',
    care: 'Machine wash cold. Hang dry or tumble low. Do not iron zipper.',
    seoTitle: 'Golf Quarter-Zip Pullover | WYX Golf Supply Co.',
    metaDescription: 'A clean midweight golf quarter-zip pullover for early tee times, cool rounds, and clubhouse wear.',
    tags: ['apparel', 'quarter zip', 'pullover', 'golf apparel', 'golf gifts', 'new arrivals']
  },
  {
    title: 'The WYX Golf Hoodie',
    handle: 'wyx-golf-hoodie',
    price: '158.00',
    badge: 'Apparel',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A heavyweight hoodie built for range sessions, post-round hangs, and the kind of golf travel where comfort matters more than looking pressed.',
    details: ['Heavyweight fleece with soft interior', 'Kangaroo pocket and ribbed cuffs', 'WYX wordmark on chest', 'Sized to layer over a polo or wear solo'],
    materials: 'French terry fleece with ribbed trims and a relaxed, slightly oversized silhouette.',
    care: 'Machine wash cold with like colors. Tumble dry low or hang dry.',
    seoTitle: 'Golf Hoodie | WYX Golf Supply Co.',
    metaDescription: 'A heavyweight WYX golf hoodie for range days, post-round hangs, and golf travel where comfort comes first.',
    tags: ['apparel', 'hoodie', 'golf apparel', 'golf gifts', 'new arrivals']
  },
  {
    title: 'Performance Golf Socks — 3 Pack',
    handle: 'performance-golf-socks-3-pack',
    price: '38.00',
    badge: 'Core Collection',
    image: imageMap.walk,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'Three pairs of no-fuss performance golf socks with arch support, cushioned sole, and a clean WYX stripe. The add-to-any-order piece that every golfer can use.',
    details: ['Cushioned sole and arch support band', 'Moisture-wicking performance knit', 'Quarter-crew height fits under pants or shorts', 'WYX stripe detail at cuff'],
    materials: 'Performance blend with nylon reinforcement at heel and toe.',
    care: 'Machine wash cold. Tumble dry low. Do not bleach.',
    seoTitle: 'Golf Socks 3-Pack | WYX Golf Supply Co.',
    metaDescription: 'Performance golf socks with arch support, cushioned sole, and a WYX stripe — a 3-pack for every round.',
    tags: ['apparel', 'socks', 'golf socks', 'golf accessories', 'golf gifts', 'core collection']
  },
  {
    title: 'Golf Alignment Sticks — 2 Pack',
    handle: 'golf-alignment-sticks',
    price: '22.00',
    badge: 'Training',
    image: imageMap.iron,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'Two 48-inch alignment sticks in high-viz orange. The single most useful range tool for fixing your stance, ball position, and swing path fast.',
    details: ['48-inch fiberglass rods', 'High-viz orange for easy feedback', 'Fits any golf bag side pocket', 'Used by tour players and weekend hackers alike'],
    materials: 'Fiberglass rod with painted finish.',
    care: 'Wipe clean after use. Store in bag pocket.',
    seoTitle: 'Golf Alignment Sticks 2-Pack | WYX Golf Supply Co.',
    metaDescription: 'Two 48-inch high-viz alignment sticks — the most useful practice tool in any golf bag. From WYX Golf Supply Co.',
    tags: ['training aids', 'alignment sticks', 'golf practice', 'range gear', 'golf gifts', 'under $60']
  },
  {
    title: 'Premium Golf Glove',
    handle: 'premium-golf-glove',
    price: '28.00',
    badge: 'Essentials',
    image: imageMap.leather,
    productType: 'Gloves',
    collectionHandle: 'accessories',
    description: 'A cabretta leather palm glove with a breathable mesh back. Fitted for control without restriction — the glove you reach for every single round.',
    details: ['Cabretta leather palm for soft grip', 'Mesh back panels for breathability', 'Ball marker embedded in Velcro closure', 'Available in S, M, L, XL'],
    materials: 'Cabretta leather palm with synthetic mesh back and Velcro closure.',
    care: 'Air dry after rounds. Store flat. Do not machine wash.',
    seoTitle: 'Premium Golf Glove | WYX Golf Supply Co.',
    metaDescription: 'A cabretta leather golf glove with a built-in ball marker and mesh back — one of the best golf gifts under $30. WYX Golf Supply Co.',
    tags: ['gloves', 'golf glove', 'cabretta leather', 'golf accessories', 'golf gifts', 'under $60', 'core collection']
  },
  {
    title: 'Golf Grip Tape Roll',
    handle: 'golf-grip-tape',
    price: '16.00',
    badge: 'Maintenance',
    image: imageMap.care,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A single roll of double-sided grip tape for re-gripping at home. Enough for a full set. Stop paying $5 a grip at the shop.',
    details: ['Double-sided adhesive, 2-inch x 36-yard roll', 'Compatible with all standard grips', 'Enough tape for a full 14-club set', 'Easy peel-and-apply application'],
    materials: 'Double-sided polyethylene tape with pressure-sensitive adhesive.',
    care: 'Store rolled in original packaging.',
    seoTitle: 'Golf Grip Tape Roll | WYX Golf Supply Co.',
    metaDescription: 'Double-sided golf grip tape for DIY re-gripping — enough for a full set. From WYX Golf Supply Co.',
    tags: ['accessories', 'grip tape', 're-gripping', 'golf maintenance', 'golf gifts', 'under $60', 'bag upgrades']
  },
  {
    title: 'Putting Alignment Mirror',
    handle: 'putting-alignment-mirror',
    price: '32.00',
    badge: 'Training',
    image: imageMap.strategy,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'A compact putting mirror with alignment lines and ball gate guides. Drop it on any putting green or living room floor and see exactly where your eyes are.',
    details: ['Hinged design folds flat for bag storage', 'Ball-gate guides force correct face angle', 'Eye position lines for consistent setup', 'Works on carpet or short grass'],
    materials: 'Polished acrylic with printed alignment guides.',
    care: 'Wipe clean with a soft cloth.',
    seoTitle: 'Putting Alignment Mirror | WYX Golf Supply Co.',
    metaDescription: 'A compact putting mirror with alignment lines and ball-gate guides. The best putting practice tool for any golfer. WYX Golf Supply Co.',
    tags: ['training aids', 'putting mirror', 'putting practice', 'golf training', 'golf gifts', 'under $60']
  },
  {
    title: 'Magnetic Golf Hat Clip & Ball Marker',
    handle: 'magnetic-hat-clip-ball-marker',
    price: '24.00',
    badge: 'Accessories',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A strong neodymium magnet hat clip that holds your ball marker on the brim. Never pat your pockets looking for your marker again.',
    details: ['Neodymium magnet with zinc alloy body', 'Includes one milled metal ball marker', 'Attaches to any hat brim in seconds', 'Low-profile design sits flush on the brim'],
    materials: 'Zinc alloy clip body with neodymium magnet and milled stainless steel marker.',
    care: 'Wipe clean. Keep away from phones and cards with magnetic strips.',
    seoTitle: 'Magnetic Golf Hat Clip & Ball Marker | WYX Golf Supply Co.',
    metaDescription: 'A magnetic hat clip with a milled metal ball marker — the easiest golf accessory upgrade in the bag. From WYX Golf Supply Co.',
    tags: ['accessories', 'ball marker', 'hat clip', 'magnetic', 'golf gifts', 'under $60', 'stocking stuffer']
  },
  {
    title: 'Golf Scorecard & Pencil Holder',
    handle: 'golf-scorecard-holder',
    price: '38.00',
    badge: 'Accessories',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A slim leather scorecard holder with a pencil loop and back pocket for a sleeve of tees. Goes right on the bag handle or in the side pocket.',
    details: ['Full-grain leather with tonal stitching', 'Pencil loop on the front', 'Back pocket for a tee sleeve', 'WYX debossed at bottom right'],
    materials: 'Full-grain vegetable-tanned leather.',
    care: 'Wipe clean. Condition with leather balm occasionally.',
    seoTitle: 'Leather Golf Scorecard Holder | WYX Golf Supply Co.',
    metaDescription: 'A slim leather golf scorecard and pencil holder with a tee pocket — a practical, gift-ready bag upgrade. WYX Golf Supply Co.',
    tags: ['accessories', 'scorecard holder', 'leather', 'golf gifts', 'under $60', 'bag upgrades', 'gifts for golfers']
  },
  {
    title: 'Golf Umbrella — 62-inch Double Canopy',
    handle: 'golf-umbrella-62-inch',
    price: '44.00',
    badge: 'Course Gear',
    image: imageMap.walk,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A 62-inch double-canopy golf umbrella with a wind-vented design and easy-grip rubber handle. Covers you and your bag without turning inside out mid-round.',
    details: ['62-inch arc covers golfer and bag', 'Double canopy venting handles wind gusts', 'Rubber grip handle for one-handed control', 'Lightweight fiberglass frame'],
    materials: 'Pongee canopy with fiberglass ribs and rubber handle.',
    care: 'Open and dry fully after use. Store upright.',
    seoTitle: '62-Inch Golf Umbrella | WYX Golf Supply Co.',
    metaDescription: 'A 62-inch double-canopy wind-vented golf umbrella with rubber grip — practical rain gear for any round. WYX Golf Supply Co.',
    tags: ['accessories', 'golf umbrella', 'course gear', 'rain gear', 'golf gifts', 'golf trip gear', 'under $60']
  },
  {
    title: 'Golf Shoe Bag',
    handle: 'golf-shoe-bag',
    price: '32.00',
    badge: 'Travel',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A zippered nylon shoe bag sized for golf spikes with a mesh ventilation panel. Keep your shoes separate from clothes on every trip.',
    details: ['Fits standard golf shoe sizes up to men\'s 14', 'Mesh ventilation panel prevents moisture buildup', 'Top carry handle and full-length zipper', 'WYX tonal logo on exterior'],
    materials: 'Ballistic nylon with mesh panel and YKK zipper.',
    care: 'Wipe clean. Air dry fully before closing.',
    seoTitle: 'Golf Shoe Bag | WYX Golf Supply Co.',
    metaDescription: 'A ventilated nylon golf shoe bag with a carry handle — practical travel gear for any golf trip. WYX Golf Supply Co.',
    tags: ['accessories', 'shoe bag', 'golf travel', 'golf trip gear', 'golf gifts', 'travel gear']
  },
  {
    title: 'Bamboo Golf Tees — 50 Pack',
    handle: 'bamboo-golf-tees-50-pack',
    price: '14.00',
    badge: 'Essentials',
    image: imageMap.care,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'Fifty 2.75-inch bamboo tees in a natural finish. Biodegradable, consistent height, and durable enough to survive multiple drives before they snap.',
    details: ['2.75-inch standard height for driver and woods', 'Bamboo construction — stronger than standard wood', 'Biodegradable and eco-friendly', 'Pack of 50 tees in a resealable bag'],
    materials: 'Natural bamboo.',
    care: 'Keep dry between rounds.',
    seoTitle: 'Bamboo Golf Tees 50-Pack | WYX Golf Supply Co.',
    metaDescription: '50 biodegradable bamboo golf tees at 2.75 inches — durable, consistent, and better for the course. From WYX Golf Supply Co.',
    tags: ['accessories', 'golf tees', 'bamboo tees', 'golf gifts', 'stocking stuffer', 'under $60', 'eco-friendly']
  },
  {
    title: 'Golf Hat Carrying Case',
    handle: 'golf-hat-carrying-case',
    price: '28.00',
    badge: 'Travel',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A rigid-shell hat box sized for one cap. Keeps your favorite round hat from getting crushed in a travel bag or stuffed in a locker.',
    details: ['Rigid outer shell with padded interior', 'Fits one fitted or adjustable cap', 'Single carry handle and magnetic closure', 'Compact enough to pack in a carry-on'],
    materials: 'ABS shell with padded interior lining.',
    care: 'Wipe clean with damp cloth.',
    seoTitle: 'Golf Hat Case | WYX Golf Supply Co.',
    metaDescription: 'A rigid-shell golf hat carrying case for travel — protect your favorite cap on every trip. WYX Golf Supply Co.',
    tags: ['accessories', 'hat case', 'golf travel', 'golf trip gear', 'golf gifts', 'headwear storage']
  },
  {
    title: 'Golf Club Brush & Groove Cleaner',
    handle: 'club-brush-groove-cleaner',
    price: '18.00',
    badge: 'Club Care',
    image: imageMap.care,
    productType: 'Club Care',
    collectionHandle: 'accessories',
    description: 'A dual-sided brush with nylon bristles on one end and a groove pick on the other. Clip it to your bag and use it on every iron, wedge, and putter.',
    details: ['Nylon bristle brush side for face and sole cleaning', 'Groove-pick side for clogged iron and wedge grooves', 'Carabiner clip attaches to any bag ring', 'Brushed zinc alloy body — won\'t rust'],
    materials: 'Zinc alloy with nylon bristles.',
    care: 'Rinse after use. Keep dry.',
    seoTitle: 'Golf Club Brush & Groove Cleaner | WYX Golf Supply Co.',
    metaDescription: 'A dual-sided club brush with groove pick and carabiner clip — practical club care gear for any bag. WYX Golf Supply Co.',
    tags: ['club care', 'club brush', 'groove cleaner', 'golf accessories', 'golf gifts', 'under $60', 'stocking stuffer']
  },

  // ── TRIP KIT PRODUCTS ────────────────────────────────────────────────────
  {
    title: 'Packable Golf Rain Jacket',
    handle: 'packable-golf-rain-jacket',
    price: '88.00',
    badge: 'Trip Essential',
    image: imageMap.hero,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A lightweight packable rain jacket that stuffs into its own chest pocket and fits inside any golf bag side pocket. Wind and water-resistant shell, clean enough for the clubhouse.',
    details: [
      'Packs into its own chest pocket — carry-on and bag-ready',
      'Wind and water-resistant bonded shell',
      'Elastic cuffs, adjustable hem drawcord',
      'Clean profile — no loud logos or bulky seams',
      'Available in Charcoal, Forest, and Black'
    ],
    materials: 'Lightweight wind and water-resistant bonded ripstop shell.',
    care: 'Machine wash cold, hang dry. Do not iron.',
    seoTitle: 'Packable Golf Rain Jacket | WYX Golf Supply Co.',
    metaDescription: 'A packable golf rain jacket that fits in any bag side pocket — wind and water-resistant, clean enough for the clubhouse, essential for golf trips.',
    tags: ['golf apparel', 'golf rain jacket', 'packable jacket', 'golf trip gear', 'golf travel', 'under $100']
  },
  {
    title: 'Golf Bag Cooler Tube',
    handle: 'golf-bag-cooler-tube',
    price: '36.00',
    badge: 'Trip Favourite',
    image: imageMap.hero,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'An insulated soft cooler tube that attaches to any golf bag side ring and holds 6 cans. Keeps drinks cold for 18 holes without leaving the bag.',
    details: [
      'Holds 6 standard cans — ice or ice pack compatible',
      'Insulated neoprene body, water-resistant lining',
      'Clips to any golf bag D-ring or side webbing',
      'Zip-top closure, wipe-clean interior',
      'Available in Black and Forest'
    ],
    materials: 'Neoprene exterior, TPU-lined insulated interior.',
    care: 'Wipe clean with a damp cloth. Air dry with zip open.',
    seoTitle: 'Golf Bag Cooler Tube | WYX Golf Supply Co.',
    metaDescription: 'An insulated golf bag cooler tube that holds 6 cans and clips to any bag side ring — the essential trip accessory for 18 holes.',
    tags: ['golf accessories', 'golf cooler', 'golf bag cooler', 'golf trip gear', 'bachelor party golf', 'golf gifts for him', 'under $60']
  },
  {
    title: 'Waterproof Golf Cart Phone Mount',
    handle: 'golf-cart-phone-mount',
    price: '28.00',
    badge: 'Tech Essential',
    image: imageMap.hero,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A waterproof magnetic phone mount that clamps to any golf cart bar or push cart handle. Holds any phone case — no wireless disruption, no vibration fall-off.',
    details: [
      'Magnetic hold with 6kg pull strength — phone stays put on bumpy cart paths',
      'IP65 waterproof rated — works in rain',
      'Universal clamp fits any cart bar diameter',
      'MagSafe-compatible magnetic disc (adapter included)',
      '360° rotation — portrait or landscape'
    ],
    materials: 'Zinc alloy body, rubber-padded clamp, neodymium magnet.',
    care: 'Wipe clean with a damp cloth.',
    seoTitle: 'Golf Cart Phone Mount | WYX Golf Supply Co.',
    metaDescription: 'A waterproof magnetic golf cart phone mount that clamps to any cart bar. MagSafe compatible, IP65 rated, 360° rotation. WYX Golf Supply Co.',
    tags: ['golf tech', 'golf accessories', 'golf cart accessories', 'golf trip gear', 'phone mount', 'golf gifts for him']
  },

  // ── DAD GIFT KIT PRODUCTS ────────────────────────────────────────────────
  {
    title: 'Full-Grain Leather Scorecard & Yardage Book Holder',
    handle: 'leather-yardage-book-holder',
    price: '54.00',
    badge: 'Dad Pick',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A full-grain leather holder that fits both a standard scorecard and a yardage book. Pencil loop on the side, snap closure, and a tee pocket on the inside cover.',
    details: [
      'Full-grain leather exterior — breaks in over time',
      'Holds standard scorecard and yardage book simultaneously',
      'Exterior pencil loop and interior tee pocket',
      'Snap closure keeps everything dry and flat',
      'Available in Tan and Black'
    ],
    materials: 'Full-grain cowhide leather with brushed brass snap.',
    care: 'Condition with leather cream once or twice a season. Wipe clean with a dry cloth.',
    seoTitle: 'Leather Scorecard & Yardage Book Holder | WYX Golf Supply Co.',
    metaDescription: 'A full-grain leather scorecard and yardage book holder with pencil loop, tee pocket, and snap closure. One of the best golf gifts under $60.',
    tags: ['golf accessories', 'scorecard holder', 'yardage book holder', 'leather golf gift', 'golf gifts for dad', 'father\'s day golf gifts', 'under $60']
  },
  {
    title: 'Personalized Ball Marker Set — 3 Milled Coins',
    handle: 'milled-ball-marker-set-3',
    price: '42.00',
    badge: 'Gift Ready',
    image: imageMap.iron,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'Three milled aluminum ball markers in different finishes — gold, silver, and gunmetal. Flat profile, 25mm diameter, no catching on the putting surface.',
    details: [
      'Three markers: brushed gold, polished silver, gunmetal matte',
      'Milled aluminum — flat profile for smooth green removal',
      '25mm diameter, 2.5mm thickness',
      'Comes in a kraft gift box — ships gift-ready',
      'Pairs with any magnetic hat clip'
    ],
    materials: 'Milled 6061 aluminum alloy with anodized finish.',
    care: 'Wipe clean with a dry cloth.',
    seoTitle: 'Milled Ball Marker Set — 3 Pack | WYX Golf Supply Co.',
    metaDescription: 'A set of three milled aluminum ball markers in gold, silver, and gunmetal. Ships in a kraft gift box — one of the best golf gifts under $50.',
    tags: ['ball markers', 'golf accessories', 'milled ball marker', 'golf gifts for dad', 'golf gifts under $50', 'stocking stuffer', 'father\'s day golf gifts']
  },

  // ── BAG UPGRADE KIT PRODUCTS ─────────────────────────────────────────────
  {
    title: 'Golf Bag Organizer Insert',
    handle: 'golf-bag-organizer-insert',
    price: '32.00',
    badge: 'Bag Upgrade',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A structured fabric insert that drops into the top pocket of any 14-way golf bag and creates 6 separated compartments for tees, markers, a divot tool, sunscreen, a phone, and snacks.',
    details: [
      'Fits any 14-way or cart bag top pocket',
      '6 separated compartments — keys, tees, marker, sunscreen, snack, misc',
      'Rigid foam base keeps it upright when the bag tips',
      'Pull-tab for fast removal at round end',
      'Available in Black and Forest'
    ],
    materials: '600D polyester shell with EVA foam base.',
    care: 'Hand wash cold. Air dry with the insert out of the bag.',
    seoTitle: 'Golf Bag Organizer Insert | WYX Golf Supply Co.',
    metaDescription: 'A structured golf bag organizer insert that creates 6 compartments in any 14-way bag pocket. One of the most practical bag upgrades under $40.',
    tags: ['golf accessories', 'bag organizer', 'golf bag insert', 'bag upgrade', 'golf gifts for dad', 'golf organization', 'under $40']
  },
  {
    title: 'Golf Grip Solvent & Tape Kit',
    handle: 'grip-solvent-tape-kit',
    price: '26.00',
    badge: 'DIY Ready',
    image: imageMap.care,
    productType: 'Grips',
    collectionHandle: 'accessories',
    description: 'Everything you need to regrip a full 14-club set at home in one afternoon: two rolls of double-sided grip tape, 8oz of grip solvent, and a vise clamp rubber insert.',
    details: [
      '2 rolls double-sided golf grip tape (covers 14+ clubs each)',
      '8oz grip solvent — activates tape for slip-on installation',
      'Rubber vise clamp insert — protects shaft in a bench vise',
      'Step-by-step regripping guide included',
      'Saves $50–$80 vs. shop regripping on a full set'
    ],
    materials: 'Double-sided rubber-based tape, petroleum-based grip solvent, molded rubber vise insert.',
    care: 'Store solvent in a cool, dry place away from flame.',
    seoTitle: 'Golf Grip Solvent & Tape Kit | WYX Golf Supply Co.',
    metaDescription: 'A complete golf regripping kit — two rolls of grip tape, 8oz solvent, and a vise insert for regripping a full set at home. Saves $50–$80 vs. shop rates.',
    tags: ['golf grips', 'grip tape', 'regripping kit', 'golf accessories', 'club maintenance', 'diy golf', 'bag upgrade', 'under $30']
  },
  {
    title: 'Groove Sharpener & Wedge Tool',
    handle: 'groove-sharpener-wedge-tool',
    price: '22.00',
    badge: 'Spin Saver',
    image: imageMap.care,
    productType: 'Club Care',
    collectionHandle: 'accessories',
    description: 'A precision groove sharpener with 6 groove widths that restores spin to worn wedges and irons — legal for recreational play and tour use.',
    details: [
      '6 groove widths from U to V-groove profiles',
      'Carbide cutting head — lasts 100+ sharpening sessions',
      'Built-in depth stop prevents over-cutting',
      'Legal for recreational and amateur tournament play',
      'Extends wedge life by 2–3 seasons'
    ],
    materials: 'Aerospace aluminum body with carbide cutting inserts.',
    care: 'Brush grooves clean before sharpening. Store in the included pouch.',
    seoTitle: 'Golf Groove Sharpener | WYX Golf Supply Co.',
    metaDescription: 'A precision golf groove sharpener with 6 widths that restores spin to worn wedges and irons. Legal for recreational play. Under $25.',
    tags: ['club care', 'groove sharpener', 'wedge maintenance', 'golf accessories', 'bag upgrade', 'golf gifts for dad', 'stocking stuffer', 'under $25']
  },
  {
    title: 'Golf GPS Watch — 40,000 Courses',
    handle: 'golf-gps-watch-40k-courses',
    price: '149.00',
    badge: 'Best Seller',
    image: imageMap.strategy,
    productType: 'Golf Tech',
    collectionHandle: 'golf-tech',
    description: 'A dedicated golf GPS watch with 40,000+ preloaded courses, auto-advance hole, front/middle/back yardages, and a battery that lasts a full round — no phone required.',
    details: [
      '40,000+ worldwide courses preloaded — no download fees',
      'Front, middle, and back yardage on every hole',
      'Auto-advance hole detection',
      'Shot distance and hazard yardages',
      'Waterproof to 5ATM — safe in rain and water traps',
      'Full-round battery life (18+ holes), charges via USB-C'
    ],
    materials: 'Silicone sport band with reinforced plastic case.',
    care: 'Rinse with fresh water after wet rounds. Charge via included USB-C cable.',
    seoTitle: 'Golf GPS Watch | 40,000 Courses | WYX Golf Supply Co.',
    metaDescription: 'A golf GPS watch with 40,000+ preloaded courses, front/middle/back yardage, and 18-hole battery life. No phone needed. Under $150.',
    tags: ['golf gps watch', 'golf tech', 'gps watch', 'golf technology', 'golf gifts for dad', 'golf gifts for him', 'rangefinder alternative', 'under $150']
  },
  {
    title: 'Collapsible Ball Retriever — 12 Ft',
    handle: 'collapsible-ball-retriever-12ft',
    price: '22.00',
    badge: 'Bag Essential',
    image: imageMap.walk,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A 12-foot telescoping golf ball retriever that collapses to 18 inches and fits in any bag side pocket. Grab balls from water hazards, deep rough, and under shrubs without sacrificing a sleeve.',
    details: [
      'Extends to 12 feet, collapses to 18 inches',
      'Fits in any bag side or water bottle pocket',
      'Ergonomic rubber grip handle',
      'Compatible with all standard golf ball sizes',
      'Aluminum shaft — rust-resistant and lightweight'
    ],
    materials: 'Anodized aluminum telescoping shaft with ABS plastic scoop head.',
    care: 'Rinse scoop after water-hazard use. Dry before collapsing for storage.',
    seoTitle: 'Golf Ball Retriever 12 Ft Collapsible | WYX Golf Supply Co.',
    metaDescription: 'A 12-foot telescoping golf ball retriever that collapses to 18 inches and fits in any bag pocket. Stops the water-hazard sacrifice. Under $25.',
    tags: ['golf ball retriever', 'collapsible ball retriever', 'golf accessories', 'golf bag essentials', 'water hazard', 'stocking stuffer', 'golf gifts under $25']
  },
  {
    title: 'UPF 50+ Golf Arm Sleeves',
    handle: 'upf50-golf-arm-sleeves',
    price: '18.00',
    badge: 'Summer Essential',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'Lightweight UPF 50+ compression arm sleeves that block 98% of UV rays, cool via moisture-wicking fabric, and slip on in seconds over any shirt — the summer round essential no golfer packs until they need them.',
    details: [
      'UPF 50+ blocks 98% of UV-A and UV-B rays',
      'Moisture-wicking compression fabric stays cool all round',
      'Slip-on fit — no buttons or closures',
      'One size fits most with 4-way stretch',
      'Machine washable; holds shape after 50+ washes'
    ],
    materials: '88% polyester / 12% spandex UV-block fabric.',
    care: 'Machine wash cold, hang dry. Avoid fabric softener.',
    seoTitle: 'Golf Arm Sleeves UPF 50+ | Sun Protection | WYX Golf Supply Co.',
    metaDescription: 'UPF 50+ golf arm sleeves that block 98% of UV rays and cool via moisture-wicking compression. Lightweight, slip-on, machine washable. Under $20.',
    tags: ['golf arm sleeves', 'upf 50', 'sun protection golf', 'golf apparel', 'summer golf', 'golf accessories', 'under $20', 'golf gifts']
  },
  {
    title: 'Insulated Golf Tumbler — 20 oz',
    handle: 'insulated-golf-tumbler-20oz',
    price: '34.00',
    badge: 'Course Ready',
    image: imageMap.hero,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A 20 oz stainless steel insulated tumbler sized to fit every cart cup holder, keep ice for 12 hours on the course, and take a logo without looking like a promotional freebie.',
    details: [
      '20 oz capacity — fits every standard cart cup holder',
      'Double-wall vacuum insulation keeps ice 12+ hours',
      '304 stainless steel — no plastic taste',
      'Sweat-proof exterior, no condensation rings on scorecards',
      'Spill-resistant slide lid, dishwasher safe body'
    ],
    materials: 'Powder-coated 304 stainless steel with BPA-free slide lid.',
    care: 'Dishwasher safe (body). Hand-wash lid. Dry inverted to prevent odor.',
    seoTitle: 'Golf Tumbler Insulated 20 oz | Cart Cup Holder | WYX Golf Supply Co.',
    metaDescription: 'A 20oz insulated golf tumbler that fits every cart cup holder, keeps ice 12 hours, and looks great on the course. Under $35.',
    tags: ['golf tumbler', 'insulated golf cup', 'golf water bottle', 'golf accessories', 'golf gifts for dad', 'golf gifts for him', 'cart cup holder', 'under $35']
  },
  {
    title: 'Polarized Golf Sunglasses',
    handle: 'polarized-golf-sunglasses',
    price: '44.00',
    badge: 'Track Every Ball',
    image: imageMap.walk,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'Wraparound polarized sunglasses built for ball tracking — high-contrast lenses cut glare off fairways and greens without darkening the sky or losing a ball in flight.',
    details: [
      'TAC polarized lenses — eliminates glare from fairways and water',
      'High-contrast tint enhances ball visibility against blue sky',
      'Lightweight TR90 frame, wraparound fit stays put through the swing',
      'UV400 protection blocks all UV-A and UV-B',
      'Includes microfiber pouch and hard case'
    ],
    materials: 'TR90 nylon frame with TAC polarized polycarbonate lenses.',
    care: 'Clean with included microfiber cloth. Store in hard case to prevent scratching.',
    seoTitle: 'Golf Sunglasses Polarized | Ball Tracking | WYX Golf Supply Co.',
    metaDescription: 'Polarized golf sunglasses with high-contrast lenses for ball tracking. Wraparound TR90 frame, UV400 protection. Under $50.',
    tags: ['golf sunglasses', 'polarized sunglasses', 'golf accessories', 'golf gifts for him', 'golf gifts for dad', 'summer golf', 'under $50', 'golf eyewear']
  },
  {
    title: 'Golf Bag Rain Hood — Universal Fit',
    handle: 'golf-bag-rain-hood-universal',
    price: '26.00',
    badge: 'Weather Ready',
    image: imageMap.towel,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A waterproof bag rain hood that fits over any stand, cart, or carry bag in seconds — clips down with bungee cord loops and keeps clubs, grips, and gear dry when the forecast lies.',
    details: [
      'Universal fit — covers stand, cart, and carry bags up to 10-inch tops',
      'Waterproof 200D polyester shell, heat-sealed seams',
      'Bungee cord loops lock it over the bag in wind',
      'Packs into a palm-sized pouch for the side pocket',
      'Includes drawstring storage pouch'
    ],
    materials: '200D waterproof polyester with heat-sealed seams and bungee loops.',
    care: 'Shake dry after use. Store in included pouch. Do not machine wash.',
    seoTitle: 'Golf Bag Rain Hood | Waterproof Bag Cover | WYX Golf Supply Co.',
    metaDescription: 'A universal waterproof golf bag rain hood that fits any stand, cart, or carry bag. Bungee lock, packs into a palm-sized pouch. Under $30.',
    tags: ['golf bag rain hood', 'golf bag cover', 'waterproof golf bag', 'golf accessories', 'golf trip', 'golf gifts', 'weather golf', 'under $30']
  }
];
