export type StarterProduct = {
  title: string;
  handle: string;
  price: string;
  badge: string;
  image: string;
  productType: string;
  collectionHandle: string;
  description: string;
  details: string[];
  materials: string;
  care: string;
  seoTitle: string;
  metaDescription: string;
  tags: string[];
};

export const imageMap = {
  hero: '/images/hero-coastal-fairway.png',
  ropeHat: '/images/rope-hat-product.png',
  polo: '/images/forest-polo-product.png',
  towel: '/images/golf-towel-product.png',
  walk: '/images/walking-golfer-lifestyle..png',
  leather: '/images/leather-bag-detail.png',
  iron: '/images/journal-iron-practice.png',
  care: '/images/journal-club-care.png',
  strategy: '/images/journal-course-strategy.png'
};

export const starterProducts: StarterProduct[] = [
  {
    title: 'The Long Game Rope Hat',
    handle: 'long-game-rope-hat',
    price: '68.00',
    badge: 'Core Collection',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A cream rope hat with restrained WYX embroidery, made for course mornings, travel days, and everything after the round.',
    details: ['Structured five-panel profile', 'Rope detail across the brim', 'Adjustable back closure', 'Designed for course, coast, and travel'],
    materials: 'Cotton canvas crown with woven rope detail and embroidered WYX mark.',
    care: 'Spot clean with cold water. Air dry away from direct heat.',
    seoTitle: 'Golf Rope Hat | WYX Golf Supply Co.',
    metaDescription: 'A premium golf rope hat with restrained WYX embroidery for early tee times, travel days, and life after the round.',
    tags: ['core collection', 'golf rope hat', 'premium golf apparel', 'headwear', 'best seller']
  },
  {
    title: 'The Fairway Polo',
    handle: 'fairway-polo',
    price: '128.00',
    badge: 'Core Collection',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A forest green polo with clean structure, quiet detail, and the kind of everyday polish that works far beyond the first tee.',
    details: ['Tailored athletic fit', 'Clean collar structure', 'Subtle WYX detail', 'Built for rounds, travel, and clubhouse evenings'],
    materials: 'Performance knit with soft hand feel and enough structure to hold its shape.',
    care: 'Machine wash cold with like colors. Hang dry or tumble low.',
    seoTitle: 'Premium Golf Polo | WYX Golf Supply Co.',
    metaDescription: 'A forest green premium golf polo with clean structure and quiet WYX detail for course and everyday wear.',
    tags: ['core collection', 'golf polo', 'premium golf apparel', 'apparel']
  },
  {
    title: 'The Waffle Golf Towel',
    handle: 'waffle-golf-towel',
    price: '42.00',
    badge: 'New',
    image: imageMap.towel,
    productType: 'Gear',
    collectionHandle: 'golf-gear',
    description: 'A premium waffle towel with forest trim, built for the bag and styled for the long game.',
    details: ['Waffle texture for club and ball cleaning', 'Bag-ready attachment loop', 'Forest trim detail', 'Sized for walking rounds and travel bags'],
    materials: 'Absorbent waffle microfiber with reinforced trim.',
    care: 'Machine wash cold. Do not use fabric softener. Air dry for best texture.',
    seoTitle: 'Premium Golf Towel | WYX Golf Supply Co.',
    metaDescription: 'A premium waffle golf towel with forest trim for clean clubs, ready gear, and quiet-luxury golf style.',
    tags: ['new arrivals', 'golf towel', 'golf accessories', 'walking golf', 'best seller']
  },
  {
    title: 'Leather Bag Tag',
    handle: 'leather-bag-tag',
    price: '54.00',
    badge: 'Limited',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A small detail with lasting presence. Built to bring a quiet mark of identity to your golf bag.',
    details: ['Leather-look finish', 'WYX identity mark', 'Bag strap included', 'Gift-ready accessory for golfers'],
    materials: 'Premium leather-style material with durable attachment hardware.',
    care: 'Wipe clean with a dry cloth. Keep away from prolonged soaking.',
    seoTitle: 'Leather Golf Bag Tag | WYX Golf Supply Co.',
    metaDescription: 'A premium leather golf bag tag made for players who value quiet detail and timeless golf accessories.',
    tags: ['limited', 'golf accessories', 'golf gifts', 'bag tag']
  },
  {
    title: 'Club Care Kit',
    handle: 'club-care-kit',
    price: '48.00',
    badge: 'Core Collection',
    image: imageMap.care,
    productType: 'Club Care',
    collectionHandle: 'club-care',
    description: 'Everything needed to keep grooves clean, gear ready, and the ritual intact.',
    details: ['Compact brush and groove tool', 'Bag-friendly cleaning cloth', 'Simple weekly reset routine', 'Designed for irons, wedges, and everyday rounds'],
    materials: 'Mixed club-care tools selected for compact carry and weekly use.',
    care: 'Rinse brush after use and dry before returning to the bag.',
    seoTitle: 'Golf Club Care Kit | WYX Golf Supply Co.',
    metaDescription: 'A compact golf club care kit for keeping grooves clean, gear ready, and the weekly golf ritual intact.',
    tags: ['core collection', 'golf club care', 'club cleaning kit', 'golf essentials']
  },
  {
    title: 'WYX Golf Ball Set',
    handle: 'wyx-golf-ball-set',
    price: '36.00',
    badge: 'New',
    image: imageMap.iron,
    productType: 'Gear',
    collectionHandle: 'golf-gear',
    description: 'A clean branded ball set for players who care about every detail, even the small ones.',
    details: ['Clean WYX mark', 'Three-ball set placeholder', 'Made for gifts, travel bags, and early rounds', 'Pairs well with towel and club care kit'],
    materials: 'Performance golf ball placeholder product for Shopify setup.',
    care: 'Keep dry and clean before play. Replace when cover wear affects performance.',
    seoTitle: 'WYX Golf Ball Set | WYX Golf Supply Co.',
    metaDescription: 'A clean WYX golf ball set for players who care about every detail in their modern golf goods.',
    tags: ['new arrivals', 'golf balls', 'golf gifts', 'golf essentials']
  },
  {
    title: 'The Course Pouch',
    handle: 'course-pouch',
    price: '42.00',
    badge: 'New Arrival',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A restrained valuables pouch for tees, markers, gloves, keys, and the small objects that make a round feel organized.',
    details: ['Compact valuables storage', 'Bag and travel friendly', 'Ideal for tees, markers, glove, wallet, and keys', 'Premium gift profile'],
    materials: 'Waxed-canvas style shell with durable zipper and soft internal structure.',
    care: 'Wipe clean. Let air dry fully before storing.',
    seoTitle: 'Golf Valuables Pouch | WYX Golf Supply Co.',
    metaDescription: 'A premium golf valuables pouch for tees, ball markers, gloves, keys, and organized walking rounds.',
    tags: ['new arrivals', 'golf valuables pouch', 'golf accessories', 'golf gifts']
  },
  {
    title: 'Divot Tool + Ball Marker Set',
    handle: 'divot-tool-ball-marker-set',
    price: '34.00',
    badge: 'Golf Gifts',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'golf-gifts',
    description: 'A clean repair tool and marker set with enough weight to feel permanent without drawing attention to itself.',
    details: ['Divot repair tool', 'Matching ball marker', 'Small, giftable, and easy to carry', 'Built around course care and quiet detail'],
    materials: 'Brass-tone metal placeholder product for supplier sampling.',
    care: 'Wipe dry after wet rounds. Store in pouch between rounds.',
    seoTitle: 'Golf Divot Tool and Ball Marker Set | WYX Golf Supply Co.',
    metaDescription: 'A premium golf divot tool and ball marker set for course care, golf gifts, and everyday carry.',
    tags: ['golf gifts', 'divot tool', 'ball marker', 'golf accessories']
  },
  {
    title: 'Golf Travel Organizer',
    handle: 'golf-travel-organizer',
    price: '58.00',
    badge: 'Travel',
    image: imageMap.walk,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A calm way to keep gloves, tees, markers, chargers, and travel-round essentials in one place.',
    details: ['Travel-ready internal organization', 'Works inside a golf bag or weekend bag', 'Built for road trips and away rounds', 'Strong premium gift potential'],
    materials: 'Durable fabric organizer with soft dividers and zipper closure placeholder.',
    care: 'Spot clean and air dry. Empty after wet rounds.',
    seoTitle: 'Golf Travel Organizer | WYX Golf Supply Co.',
    metaDescription: 'A premium golf travel organizer for road trips, away rounds, golf accessories, and course essentials.',
    tags: ['travel', 'golf accessories', 'golf gifts', 'new arrivals']
  },
  {
    title: 'Swing Tempo Trainer',
    handle: 'swing-tempo-trainer',
    price: '44.00',
    badge: 'Training',
    image: imageMap.iron,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'A simple tempo tool that grooves a repeatable swing rhythm. Useful for range sessions, pre-round warmups, and fixing bad habits before they cost strokes.',
    details: ['Weighted tip builds feel for the transition point', 'Works with irons, wedges, and short clubs', 'Compact enough for the bag or travel case', 'Good gift for players serious about improvement'],
    materials: 'Fiberglass shaft with weighted tip and rubber grip.',
    care: 'Wipe clean after use. Store in bag pocket or travel sleeve.',
    seoTitle: 'Golf Swing Tempo Trainer | WYX Golf Supply Co.',
    metaDescription: 'A golf swing tempo trainer for building a repeatable rhythm at the range, pre-round warmup, and home practice.',
    tags: ['training', 'swing trainer', 'training aid', 'golf gifts', 'range gear', 'new arrivals']
  },
  {
    title: 'Laser Rangefinder',
    handle: 'laser-rangefinder',
    price: '129.00',
    badge: 'Golf Tech',
    image: imageMap.strategy,
    productType: 'Golf Tech',
    collectionHandle: 'golf-tech',
    description: 'A clean, pin-seeking laser rangefinder that gives instant yardage to the flag, hazards, and layup targets. The practical upgrade that changes how you think about every approach.',
    details: ['Pin-seeker technology locks to the flag', 'Reads to ±1 yard accuracy', 'Compact and lightweight for bag or pocket carry', 'Strong gift candidate for the serious weekend golfer'],
    materials: 'Durable polymer housing with optical lens and rechargeable or battery power.',
    care: 'Keep dry. Clean lens with soft cloth. Store in included case.',
    seoTitle: 'Golf Laser Rangefinder | WYX Golf Supply Co.',
    metaDescription: 'A compact golf laser rangefinder with pin-seeker technology for accurate yardages on every approach shot.',
    tags: ['golf tech', 'rangefinder', 'laser rangefinder', 'golf gifts', 'dad gifts', 'new arrivals']
  },
  {
    title: 'The Links Snapback',
    handle: 'links-snapback',
    price: '58.00',
    badge: 'Headwear',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A flat-brim snapback with a clean WYX mark. Structured enough for the course, relaxed enough for the rest of the day.',
    details: ['Flat brim with structured crown', 'Snapback closure fits most', 'Embroidered WYX front panel', 'Available in forest and sand colorways'],
    materials: 'Cotton twill crown with embroidered WYX detail and plastic snapback closure.',
    care: 'Spot clean with cold water. Air dry away from direct heat.',
    seoTitle: 'Golf Snapback Hat | WYX Golf Supply Co.',
    metaDescription: 'A flat-brim golf snapback with embroidered WYX detail for course wear, travel days, and everyday carry.',
    tags: ['headwear', 'hat', 'cap', 'golf hat', 'snapback', 'golf gifts', 'new arrivals']
  },
  {
    title: 'The Dad Fit Cap',
    handle: 'dad-fit-cap',
    price: '52.00',
    badge: 'Dad Gifts',
    image: imageMap.ropeHat,
    productType: 'Headwear',
    collectionHandle: 'headwear',
    description: 'A six-panel unstructured cap with a curved brim. The comfortable, easygoing hat that looks right on the course and off it.',
    details: ['Unstructured six-panel build', 'Pre-curved brim for a broken-in feel', 'Brass buckle back closure', 'Golf dad\'s go-to round hat'],
    materials: 'Garment-washed cotton with tonal embroidery and brass hardware.',
    care: 'Hand wash cold. Air dry. Do not tumble dry.',
    seoTitle: 'Golf Dad Cap | WYX Golf Supply Co.',
    metaDescription: 'A garment-washed unstructured golf dad cap with a curved brim and brass closure — a perfect golf gift for dad.',
    tags: ['headwear', 'hat', 'cap', 'golf hat', 'dad gifts', 'golf gifts for dad', 'new arrivals']
  },
  {
    title: 'The Course Quarter-Zip',
    handle: 'course-quarter-zip',
    price: '148.00',
    badge: 'Apparel',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A course-ready quarter-zip in a midweight performance knit. Clean enough for the clubhouse, warm enough for early tee times and coastal evenings.',
    details: ['Quarter-zip collar with clean pull', 'Midweight warmth for cool rounds', 'Relaxed athletic fit over a polo or base layer', 'WYX tonal detail at chest'],
    materials: 'Midweight performance knit with moisture management and stretch.',
    care: 'Machine wash cold. Hang dry or tumble low. Do not iron zipper.',
    seoTitle: 'Golf Quarter-Zip Pullover | WYX Golf Supply Co.',
    metaDescription: 'A clean midweight golf quarter-zip pullover for early tee times, cool rounds, and clubhouse wear.',
    tags: ['apparel', 'quarter zip', 'pullover', 'golf apparel', 'golf gifts', 'new arrivals']
  },
  {
    title: 'The WYX Golf Hoodie',
    handle: 'wyx-golf-hoodie',
    price: '158.00',
    badge: 'Apparel',
    image: imageMap.polo,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'A heavyweight hoodie built for range sessions, post-round hangs, and the kind of golf travel where comfort matters more than looking pressed.',
    details: ['Heavyweight fleece with soft interior', 'Kangaroo pocket and ribbed cuffs', 'WYX wordmark on chest', 'Sized to layer over a polo or wear solo'],
    materials: 'French terry fleece with ribbed trims and a relaxed, slightly oversized silhouette.',
    care: 'Machine wash cold with like colors. Tumble dry low or hang dry.',
    seoTitle: 'Golf Hoodie | WYX Golf Supply Co.',
    metaDescription: 'A heavyweight WYX golf hoodie for range days, post-round hangs, and golf travel where comfort comes first.',
    tags: ['apparel', 'hoodie', 'golf apparel', 'golf gifts', 'new arrivals']
  },
  {
    title: 'Performance Golf Socks — 3 Pack',
    handle: 'performance-golf-socks-3-pack',
    price: '38.00',
    badge: 'Core Collection',
    image: imageMap.walk,
    productType: 'Apparel',
    collectionHandle: 'apparel',
    description: 'Three pairs of no-fuss performance golf socks with arch support, cushioned sole, and a clean WYX stripe. The add-to-any-order piece that every golfer can use.',
    details: ['Cushioned sole and arch support band', 'Moisture-wicking performance knit', 'Quarter-crew height fits under pants or shorts', 'WYX stripe detail at cuff'],
    materials: 'Performance blend with nylon reinforcement at heel and toe.',
    care: 'Machine wash cold. Tumble dry low. Do not bleach.',
    seoTitle: 'Golf Socks 3-Pack | WYX Golf Supply Co.',
    metaDescription: 'Performance golf socks with arch support, cushioned sole, and a WYX stripe — a 3-pack for every round.',
    tags: ['apparel', 'socks', 'golf socks', 'golf accessories', 'golf gifts', 'core collection']
  },
  {
    title: 'Golf Alignment Sticks — 2 Pack',
    handle: 'golf-alignment-sticks',
    price: '22.00',
    badge: 'Training',
    image: imageMap.iron,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'Two 48-inch alignment sticks in high-viz orange. The single most useful range tool for fixing your stance, ball position, and swing path fast.',
    details: ['48-inch fiberglass rods', 'High-viz orange for easy feedback', 'Fits any golf bag side pocket', 'Used by tour players and weekend hackers alike'],
    materials: 'Fiberglass rod with painted finish.',
    care: 'Wipe clean after use. Store in bag pocket.',
    seoTitle: 'Golf Alignment Sticks 2-Pack | WYX Golf Supply Co.',
    metaDescription: 'Two 48-inch high-viz alignment sticks — the most useful practice tool in any golf bag. From WYX Golf Supply Co.',
    tags: ['training aids', 'alignment sticks', 'golf practice', 'range gear', 'golf gifts', 'under $60']
  },
  {
    title: 'Premium Golf Glove',
    handle: 'premium-golf-glove',
    price: '28.00',
    badge: 'Essentials',
    image: imageMap.leather,
    productType: 'Gloves',
    collectionHandle: 'accessories',
    description: 'A cabretta leather palm glove with a breathable mesh back. Fitted for control without restriction — the glove you reach for every single round.',
    details: ['Cabretta leather palm for soft grip', 'Mesh back panels for breathability', 'Ball marker embedded in Velcro closure', 'Available in S, M, L, XL'],
    materials: 'Cabretta leather palm with synthetic mesh back and Velcro closure.',
    care: 'Air dry after rounds. Store flat. Do not machine wash.',
    seoTitle: 'Premium Golf Glove | WYX Golf Supply Co.',
    metaDescription: 'A cabretta leather golf glove with a built-in ball marker and mesh back — one of the best golf gifts under $30. WYX Golf Supply Co.',
    tags: ['gloves', 'golf glove', 'cabretta leather', 'golf accessories', 'golf gifts', 'under $60', 'core collection']
  },
  {
    title: 'Golf Grip Tape Roll',
    handle: 'golf-grip-tape',
    price: '16.00',
    badge: 'Maintenance',
    image: imageMap.care,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A single roll of double-sided grip tape for re-gripping at home. Enough for a full set. Stop paying $5 a grip at the shop.',
    details: ['Double-sided adhesive, 2-inch x 36-yard roll', 'Compatible with all standard grips', 'Enough tape for a full 14-club set', 'Easy peel-and-apply application'],
    materials: 'Double-sided polyethylene tape with pressure-sensitive adhesive.',
    care: 'Store rolled in original packaging.',
    seoTitle: 'Golf Grip Tape Roll | WYX Golf Supply Co.',
    metaDescription: 'Double-sided golf grip tape for DIY re-gripping — enough for a full set. From WYX Golf Supply Co.',
    tags: ['accessories', 'grip tape', 're-gripping', 'golf maintenance', 'golf gifts', 'under $60', 'bag upgrades']
  },
  {
    title: 'Putting Alignment Mirror',
    handle: 'putting-alignment-mirror',
    price: '32.00',
    badge: 'Training',
    image: imageMap.strategy,
    productType: 'Training Aids',
    collectionHandle: 'training-aids',
    description: 'A compact putting mirror with alignment lines and ball gate guides. Drop it on any putting green or living room floor and see exactly where your eyes are.',
    details: ['Hinged design folds flat for bag storage', 'Ball-gate guides force correct face angle', 'Eye position lines for consistent setup', 'Works on carpet or short grass'],
    materials: 'Polished acrylic with printed alignment guides.',
    care: 'Wipe clean with a soft cloth.',
    seoTitle: 'Putting Alignment Mirror | WYX Golf Supply Co.',
    metaDescription: 'A compact putting mirror with alignment lines and ball-gate guides. The best putting practice tool for any golfer. WYX Golf Supply Co.',
    tags: ['training aids', 'putting mirror', 'putting practice', 'golf training', 'golf gifts', 'under $60']
  },
  {
    title: 'Magnetic Golf Hat Clip & Ball Marker',
    handle: 'magnetic-hat-clip-ball-marker',
    price: '24.00',
    badge: 'Accessories',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A strong neodymium magnet hat clip that holds your ball marker on the brim. Never pat your pockets looking for your marker again.',
    details: ['Neodymium magnet with zinc alloy body', 'Includes one milled metal ball marker', 'Attaches to any hat brim in seconds', 'Low-profile design sits flush on the brim'],
    materials: 'Zinc alloy clip body with neodymium magnet and milled stainless steel marker.',
    care: 'Wipe clean. Keep away from phones and cards with magnetic strips.',
    seoTitle: 'Magnetic Golf Hat Clip & Ball Marker | WYX Golf Supply Co.',
    metaDescription: 'A magnetic hat clip with a milled metal ball marker — the easiest golf accessory upgrade in the bag. From WYX Golf Supply Co.',
    tags: ['accessories', 'ball marker', 'hat clip', 'magnetic', 'golf gifts', 'under $60', 'stocking stuffer']
  },
  {
    title: 'Golf Scorecard & Pencil Holder',
    handle: 'golf-scorecard-holder',
    price: '38.00',
    badge: 'Accessories',
    image: imageMap.leather,
    productType: 'Accessories',
    collectionHandle: 'accessories',
    description: 'A slim leather scorecard holder with a pencil loop and back pocket for a sleeve of tees. Goes right on the bag handle or in the side pocket.',
    details: ['Full-grain leather with tonal stitching', 'Pencil loop on the front', 'Back pocket for a tee sleeve', 'WYX debossed at bottom right'],
    materials: 'Full-grain vegetable-tanned leather.',
    care: 'Wipe clean. Condition with leather balm occasionally.',
    seoTitle: 'Leather Golf Scorecard Holder | WYX Golf Supply Co.',
    metaDescription: 'A slim leather golf scorecard and pencil holder with a tee pocket — a practical, gift-ready bag upgrade. WYX Golf Supply Co.',
    tags: ['accessories', 'scorecard holder', 'leather', 'golf gifts', 'under $60', 'bag upgrades', 'gifts for golfers']
  }
];
